/**
 * test/client-build.test.ts — build-contract smoke test for `lib/client.js`.
 *
 * `lib/client.js` is generated by `scripts/build-client.mjs` (esbuild) and is
 * what the dsh web shell loads via `package.json.dsh.client` →
 * `exports["./client"]`. A regression here (e.g. forgetting the
 * `__ModuleLoader__.load` wrapper) makes the GUI hard-fail at import time:
 *
 *   bundle ... loaded without registering "iterate-plugin" via __ModuleLoader__.load
 *
 * These tests load the built artifact in a Node `vm` sandbox with a fake
 * `window.__ModuleLoader__`, invoke the factory with a fake `require`, and
 * assert the standard module contract (name / inject / apply) is exported.
 * No real DOM is required — the bundle's UI functions are never called, only
 * the module surface is inspected.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import vm from 'node:vm'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const clientPath = resolve(root, 'lib/client.js')

/** Snapshot from loading the bundle inside a real `window.__ModuleLoader__`. */
interface LoadSnapshot {
  registeredId: string | null
  exports: Record<string, unknown> | null
  required: string[]
}

function loadClient(): LoadSnapshot {
  const code = readFileSync(clientPath, 'utf8')
  const snapshot: LoadSnapshot = { registeredId: null, exports: null, required: [] }

  const sandbox = {
    window: {
      __ModuleLoader__: {
        load(args: { id: string; factory: (require: (spec: string) => unknown) => unknown }) {
          snapshot.registeredId = args.id
          // React is an external resolved by the shell; a stub object is enough
          // to surface the module exports without running the UI.
          const fakeRequire = (spec: string): unknown => {
            snapshot.required.push(spec)
            if (spec === 'react' || spec === 'react/jsx-runtime' || spec === 'react-dom/client') return {}
            throw new Error(`unexpected external require: ${spec}`)
          }
          snapshot.exports = args.factory(fakeRequire) as Record<string, unknown>
        },
      },
    },
  }

  const context = vm.createContext(sandbox)
  vm.runInContext(code, context, { filename: 'client.js' })
  return snapshot
}

test('lib/client.js registers itself with the __ModuleLoader__ loader id "iterate-plugin"', () => {
  const code = readFileSync(clientPath, 'utf8')
  assert.match(
    code,
    /window\.__ModuleLoader__\.load\(\{ id: "iterate-plugin", factory: \(require\) =>/,
    'artifact must open with the __ModuleLoader__.load registration',
  )
})

test('lib/client.js exports the standard module contract (name / inject / apply)', () => {
  const snapshot = loadClient()
  assert.equal(snapshot.registeredId, 'iterate-plugin')
  assert.ok(snapshot.exports, 'factory should return module.exports')
  assert.equal(snapshot.exports.name, 'iterate-plugin')
  // `inject` is an array from the vm realm — copy it into the host realm so
  // deepEqual compares plain values (prototypes differ across realms).
  assert.deepEqual([...(snapshot.exports.inject as unknown[])], ['slots'])
  assert.equal(typeof snapshot.exports.apply, 'function')
})

test('lib/client.js only requires the shell-provided react externals', () => {
  const snapshot = loadClient()
  for (const spec of snapshot.required) {
    assert.ok(
      spec === 'react' || spec === 'react/jsx-runtime' || spec === 'react-dom/client',
      `unexpected local/external require at runtime: ${spec}`,
    )
  }
})