/**
 * test/client-build.test.ts — build-contract smoke test for `lib/client.js`.
 *
 * `lib/client.js` is generated by `scripts/build-client.mjs` (esbuild) and is
 * what the dsh web shell loads via `package.json.dsh.client` →
 * `exports["./client"]`. A regression here (e.g. forgetting the
 * `__ModuleLoader__.load` wrapper) makes the GUI hard-fail at import time:
 *
 *   bundle ... loaded without registering "iterate-plugin" via __ModuleLoader__.load
 *
 * These tests load the built artifact in a Node `vm` sandbox with a fake
 * `window.__ModuleLoader__`, invoke the factory with a fake `require`, and
 * assert the standard module contract (name / inject / apply) is exported.
 * No real DOM is required — the bundle's UI functions are never called, only
 * the module surface is inspected.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import vm from 'node:vm'
import test from 'node:test'
import assert from 'node:assert/strict'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const clientPath = resolve(root, 'lib/client.js')

/** Snapshot from loading the bundle inside a real `window.__ModuleLoader__`. */
interface LoadSnapshot {
  registeredId: string | null
  exports: Record<string, unknown> | null
  required: string[]
}

function loadClient(): LoadSnapshot {
  const code = readFileSync(clientPath, 'utf8')
  const snapshot: LoadSnapshot = { registeredId: null, exports: null, required: [] }

  const sandbox = {
    window: {
      __ModuleLoader__: {
        load(args: { id: string; factory: (require: (spec: string) => unknown) => unknown }) {
          snapshot.registeredId = args.id
          // React is an external resolved by the shell; a stub object is enough
          // to surface the module exports without running the UI.
          const fakeRequire = (spec: string): unknown => {
            snapshot.required.push(spec)
            if (spec === 'react' || spec === 'react/jsx-runtime' || spec === 'react-dom/client') return {}
            throw new Error(`unexpected external require: ${spec}`)
          }
          snapshot.exports = args.factory(fakeRequire) as Record<string, unknown>
        },
      },
    },
  }

  const context = vm.createContext(sandbox)
  vm.runInContext(code, context, { filename: 'client.js' })
  return snapshot
}

test('lib/client.js registers itself with the __ModuleLoader__ loader id "iterate-plugin"', () => {
  const code = readFileSync(clientPath, 'utf8')
  assert.match(
    code,
    /window\.__ModuleLoader__\.load\(\{ id: "iterate-plugin", factory: \(require\) =>/,
    'artifact must open with the __ModuleLoader__.load registration',
  )
})

test('lib/client.js exports the standard module contract (name / inject / apply)', () => {
  const snapshot = loadClient()
  assert.equal(snapshot.registeredId, 'iterate-plugin')
  assert.ok(snapshot.exports, 'factory should return module.exports')
  assert.equal(snapshot.exports.name, 'iterate-plugin')
  // `inject` is an array from the vm realm — copy it into the host realm so
  // deepEqual compares plain values (prototypes differ across realms).
  assert.deepEqual([...(snapshot.exports.inject as unknown[])], ['slots', 'theme'])
  assert.equal(typeof snapshot.exports.apply, 'function')
})

test('lib/client.js only requires the shell-provided react externals', () => {
  const snapshot = loadClient()
  for (const spec of snapshot.required) {
    assert.ok(
      spec === 'react' || spec === 'react/jsx-runtime' || spec === 'react-dom/client',
      `unexpected local/external require at runtime: ${spec}`,
    )
  }
})

// ─── UX gap-fix surface shipped inside the bundle ───────────────────────────
//
// These guard the pieces of gaps #1/#4/#6/#11/#13/#14 that only exist in the
// built artifact (the shell never imports `src/client/index.ts` directly).
//
// esbuild escapes non-ASCII as `\uXXXX` (uppercase hex), so every Chinese
// needle has to be checked in both raw and escaped form.

/** Encode `text` the way esbuild escapes non-ASCII string literals. */
function esbuildEscaped(text: string): string {
  let out = ''
  for (const ch of text) {
    const code = ch.codePointAt(0) ?? 0
    out += code > 0x7e
      ? '\\u' + code.toString(16).toUpperCase().padStart(4, '0')
      : ch
  }
  return out
}

function bundleHas(code: string, text: string): boolean {
  return code.includes(text) || code.includes(esbuildEscaped(text))
}

function assertBundleHas(code: string, text: string, why: string): void {
  assert.ok(bundleHas(code, text), `${why}: missing "${text}"`)
}

test('lib/client.js ships the Fn tab labels and digit hotkey map (gap #14)', () => {
  const code = readFileSync(clientPath, 'utf8')
  // Labels are rendered as `F{n} {label}` at runtime, so assert the pieces:
  // every panel label, the number prefix helper, and the digit hotkey map.
  for (const label of ['审查线程', '断点恢复', '质量门禁', '防御事件', '经验银行']) {
    assertBundleHas(code, label, 'tab label')
  }
  assert.ok(code.includes('toUpperCase()'), 'tab labels must be prefixed with their Fn number')
  assert.ok(/0:\s*"f10"/.test(code), 'digit hotkey map (0 → F10) missing')
  assert.ok(/"-":\s*"live"/.test(code), 'digit hotkey map (- → live feed) missing')
  assert.ok(code.includes('iterate-obs-tab'), 'tab rendering missing')
  assert.ok(code.includes('aria-selected'), 'tabs must expose their selected state')
})

test('lib/client.js ships the disk-snapshot pull instruction (gap #4)', () => {
  const code = readFileSync(clientPath, 'utf8')
  assertBundleHas(code, '拉取磁盘快照', 'pull-snapshot action')
  for (const tool of ['iterate_status', 'iterate_transcript', 'iterate_quality_gate', 'iterate_experience', 'iterate_defense_events']) {
    assert.ok(code.includes(tool), `${tool} missing from the bundled pull instruction`)
  }
  assertBundleHas(code, '尚未从磁盘拉取', 'empty states must distinguish "not pulled" from "empty"')
})

test('lib/client.js renders validation rows and the cross-round comparison (gaps #6/#13)', () => {
  const code = readFileSync(clientPath, 'utf8')
  assertBundleHas(code, '验证结果', 'F6 validation block')
  assert.ok(code.includes('aborted_by_validation'), 'failure highlight condition missing')
  assertBundleHas(code, '跨轮对比', 'cross-round comparison table')
})

test('lib/client.js export payload carries the four on-disk artifacts (gap #11)', () => {
  const code = readFileSync(clientPath, 'utf8')
  for (const key of ['qualityGate', 'experienceBank', 'defenseEvents', 'report']) {
    assert.ok(new RegExp(`\\b${key}\\b`).test(code), `export key ${key} missing`)
  }
})

test('lib/client.js copies the registered startup instructions, not a slash command (gap #1)', () => {
  const code = readFileSync(clientPath, 'utf8')
  assert.ok(code.includes('START_INSTRUCTIONS'), 'startup instruction registry missing')
  assert.ok(code.includes('workflow'), 'startup text must route through the workflow tool')
  assert.ok(!/copy\(key,\s*['"]\/iterate/.test(code), 'no slash-command copy path')
})